### PR TITLE
"Clickable" kothic layer

### PR DESCRIPTION
**Pull request by nickw1**
L.TileLayer.Kothic.Clickable has been created with is a "clickable" kothic layer. It extends from L.TileLayer.Kothic. With this layer, when a mouse click takes place near a POI (distance in pixels can be specified in the options), a "featureclick" event is fired. The intention is to produce kothic maps with clickable POIs (e.g. producing a popup). For example see http://www.free-map.org.uk/ and try clicking on any pub.

### CODE REVIEW

**Comment by DerDakon** [comment]
There are some whitespace errors, you can easily spot them using "git diff --color=always master..".

The second and third commit only modify the first one, yet the last one reverts it back to what it was in the first commit. Please clean that up.

I'll do some testing with it when I find time.

**Comment by DerDakon** [comment]
Seems to work nicely for me.

**Comment by nickw1** [comment]
Sorry, don't know how that happened, must have been a sync issue - will fix it. The last commit should be on top of the third one.

**Comment by nickw1** [comment]
Have resolved the inconsistencies above with the first few commits, I think all whitespace issues are now resolved.

**Comment by DerDakon** [comment]
Please squash the coding style fixes into those comments that introduced them, keeping only the development progress in the commits.

**Comment by nickw1** [comment]
OK have squashed into 2 commits; the original development plus the addition of POIs only.

**Comment by DerDakon** [comment]
There are leftovers in the commit message, also the second commit contains some whitespace fixes to the first commit, they should better go there so there is less noise.

**Comment by nickw1** [comment]
Apologies for never cleaning this up. Will try and do it soon if I can.

**Comment by nickw1** [comment]
Closing this and recreating new one based on single commit

**Pull request closed without merging**
